/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlhoinghi.ui;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import qlhoinghi.util.HibernateUtil;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.Session;
import org.hibernate.Query;
import qlhoinghi.entity.DiaDiem;
import qlhoinghi.entity.HoiNghi;
import qlhoinghi.entity.TaiKhoan;
/**
 *
 * @author admin
 */
public class LichSuDangKy extends javax.swing.JFrame {

    /**
     * Creates new form LichSuDangKy
     */
    public LichSuDangKy() {
        initComponents();
    }
    public LichSuDangKy(String username,String id) {
        initComponents();
        tkLichSu.setText(username);
        matkLichSu.setText(id);
        matkLichSu.setVisible(false);
        dxLichSu.setVisible(true);
        tenls.setText("");
        motals.setText("");
        diadiemls.setText("");
        ngaydauls.setDate(null);
        ngaysauls.setDate(null);
        xacnhanls.setSelectedItem("Tất cả");
        if(tkLichSu.getText().compareTo("admin")!=0)
        {
            qlhnls.setVisible(false);
            qluserls.setVisible(false);
        }
        else
        {
            qlhnls.setVisible(true);
            qluserls.setVisible(true);
        }
        displayTable();
    }
    public void displayTable()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery("select h,d.ten,y.xacNhan from YeuCau y join y.taiKhoan t join y.hoiNghi h "
                + "join h.diaDiem d where t.username =:username")
                .setParameter("username", tkLichSu.getText());
        List<Object[]> resultList = q.list();
        session.getTransaction().commit();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Mã hội nghị"); 
        tableHeaders.add("Tên hội nghị"); 
        tableHeaders.add("Mô tả"); 
        tableHeaders.add("Thời gian bắt đầu");
        tableHeaders.add("Thời gian kết thúc"); 
        tableHeaders.add("Địa điểm");
        tableHeaders.add("Xác nhận"); 
        for(Object[] o : resultList) {
            HoiNghi h =(HoiNghi)o[0];
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(h.getId());
            oneRow.add(h.getTen());
            oneRow.add(h.getMoTaNgan());
            oneRow.add(h.getThoiGianBatDau());
            oneRow.add(h.getThoiGianKetThuc());
            oneRow.add(o[1]);
            oneRow.add(o[2]);
            tableData.add(oneRow);
        }
        resultTablels.setModel(new DefaultTableModel(tableData, tableHeaders));
        resultTablels.setDefaultEditor(Object.class, null);
        resultTablels.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 18));
        resultTablels.setAutoCreateRowSorter(true);
        lsdkls.setBackground(new java.awt.Color(204,204,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        manHinhChiTietHoiNghi = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moTa = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        thamduTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ma = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diaDiem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        batDau = new javax.swing.JLabel();
        ketThuc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ten = new javax.swing.JLabel();
        huydk = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        homels = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        profilels = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        qlhnls = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        qluserls = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lsdkls = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tkLichSu = new javax.swing.JLabel();
        dxLichSu = new javax.swing.JButton();
        matkLichSu = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        ngaydauls = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        tenls = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        motals = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        diadiemls = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ngaysauls = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        xacnhanls = new javax.swing.JComboBox<>();
        timkiemls = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultTablels = new javax.swing.JTable();

        manHinhChiTietHoiNghi.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        manHinhChiTietHoiNghi.setTitle("Chi tiết hội nghị");
        manHinhChiTietHoiNghi.setMinimumSize(new java.awt.Dimension(966, 468));
        manHinhChiTietHoiNghi.setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        moTa.setEditable(false);
        moTa.setBackground(new java.awt.Color(153, 153, 255));
        moTa.setBorder(null);
        moTa.setDisabledTextColor(new java.awt.Color(0, 51, 51));
        jScrollPane2.setViewportView(moTa);

        thamduTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên người tham dự", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(thamduTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Mã hội nghị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel2, gridBagConstraints);

        ma.setText("đây là mã");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(ma, gridBagConstraints);

        jLabel3.setText("Địa điểm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel3, gridBagConstraints);

        diaDiem.setText("đây là địa điẻm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(diaDiem, gridBagConstraints);

        jLabel5.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel5, gridBagConstraints);

        diaChi.setText("đây là địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(diaChi, gridBagConstraints);

        jLabel7.setText("Thời gian từ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel7, gridBagConstraints);

        batDau.setText("bắt đầu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        jPanel4.add(batDau, gridBagConstraints);

        ketThuc.setText("kết thúc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        jPanel4.add(ketThuc, gridBagConstraints);

        jLabel10.setText(" - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel4.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        jPanel4.add(jLabel4, gridBagConstraints);

        jLabel6.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel19.setText("Tên hội nghị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel19, gridBagConstraints);

        ten.setText("đây là tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(ten, gridBagConstraints);

        huydk.setText("Hủy đăng ký");
        huydk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huydkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(huydk, gridBagConstraints);

        javax.swing.GroupLayout manHinhChiTietHoiNghiLayout = new javax.swing.GroupLayout(manHinhChiTietHoiNghi.getContentPane());
        manHinhChiTietHoiNghi.getContentPane().setLayout(manHinhChiTietHoiNghiLayout);
        manHinhChiTietHoiNghiLayout.setHorizontalGroup(
            manHinhChiTietHoiNghiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manHinhChiTietHoiNghiLayout.createSequentialGroup()
                .addGroup(manHinhChiTietHoiNghiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manHinhChiTietHoiNghiLayout.setVerticalGroup(
            manHinhChiTietHoiNghiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manHinhChiTietHoiNghiLayout.createSequentialGroup()
                .addGroup(manHinhChiTietHoiNghiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, manHinhChiTietHoiNghiLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lịch sử đăng ký");
        setResizable(false);

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));

        homels.setBackground(new java.awt.Color(102, 102, 255));
        homels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homelsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homelsMouseExited(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(204, 204, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-24 (1).png"))); // NOI18N
        jLabel31.setText("Trang chủ");

        javax.swing.GroupLayout homelsLayout = new javax.swing.GroupLayout(homels);
        homels.setLayout(homelsLayout);
        homelsLayout.setHorizontalGroup(
            homelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homelsLayout.setVerticalGroup(
            homelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homelsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        profilels.setBackground(new java.awt.Color(102, 102, 255));
        profilels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilelsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilelsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilelsMouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-male-user-24.png"))); // NOI18N
        jLabel32.setText("Profile");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout profilelsLayout = new javax.swing.GroupLayout(profilels);
        profilels.setLayout(profilelsLayout);
        profilelsLayout.setHorizontalGroup(
            profilelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profilelsLayout.setVerticalGroup(
            profilelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilelsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32))
        );

        qlhnls.setBackground(new java.awt.Color(102, 102, 255));
        qlhnls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlhnlsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qlhnlsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qlhnlsMouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-management-24.png"))); // NOI18N
        jLabel33.setText("Quản lý hội nghị");

        javax.swing.GroupLayout qlhnlsLayout = new javax.swing.GroupLayout(qlhnls);
        qlhnls.setLayout(qlhnlsLayout);
        qlhnlsLayout.setHorizontalGroup(
            qlhnlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        qlhnlsLayout.setVerticalGroup(
            qlhnlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlhnlsLayout.createSequentialGroup()
                .addComponent(jLabel33)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        qluserls.setBackground(new java.awt.Color(102, 102, 255));
        qluserls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qluserlsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qluserlsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qluserlsMouseExited(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-management-24 (1).png"))); // NOI18N
        jLabel34.setText("Quản lý user");

        javax.swing.GroupLayout qluserlsLayout = new javax.swing.GroupLayout(qluserls);
        qluserls.setLayout(qluserlsLayout);
        qluserlsLayout.setHorizontalGroup(
            qluserlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        qluserlsLayout.setVerticalGroup(
            qluserlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qluserlsLayout.createSequentialGroup()
                .addComponent(jLabel34)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lsdkls.setBackground(new java.awt.Color(102, 102, 255));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-activity-history-24.png"))); // NOI18N
        jLabel35.setText("Lịch sử đăng ký");

        javax.swing.GroupLayout lsdklsLayout = new javax.swing.GroupLayout(lsdkls);
        lsdkls.setLayout(lsdklsLayout);
        lsdklsLayout.setHorizontalGroup(
            lsdklsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lsdklsLayout.setVerticalGroup(
            lsdklsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsdklsLayout.createSequentialGroup()
                .addComponent(jLabel35)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lsdkls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profilels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qlhnls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qluserls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(homels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(profilels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lsdkls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(qlhnls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(qluserls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 51));

        tkLichSu.setText("đây là tk");

        dxLichSu.setText("Đăng xuất");
        dxLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxLichSuActionPerformed(evt);
            }
        });

        matkLichSu.setText("đây là mã");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(744, Short.MAX_VALUE)
                .addComponent(matkLichSu)
                .addGap(31, 31, 31)
                .addComponent(tkLichSu)
                .addGap(18, 18, 18)
                .addComponent(dxLichSu)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dxLichSu)
                    .addComponent(tkLichSu)
                    .addComponent(matkLichSu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTextFieldDateEditor editor = (JTextFieldDateEditor) ngaydauls.getDateEditor();
        editor.setEditable(false);

        jLabel25.setText("Tên hội nghị");

        jLabel26.setText("Mô tả");

        jLabel27.setText("Địa điểm");

        jLabel28.setText("Ngày bắt đầu từ");

        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) ngaysauls.getDateEditor();
        editor1.setEditable(false);

        jLabel29.setText("đến");

        jLabel30.setText("Xác nhận");

        xacnhanls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đồng ý", "Không đồng ý", "Đang chờ" }));
        xacnhanls.setToolTipText("");

        timkiemls.setText("Tìm kiếm");
        timkiemls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemlsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(motals, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(32, 32, 32)
                                .addComponent(tenls, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(diadiemls, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ngaydauls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(xacnhanls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ngaysauls, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(timkiemls)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tenls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(diadiemls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(xacnhanls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel26)
                                        .addComponent(motals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28))
                                    .addComponent(ngaydauls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ngaysauls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(timkiemls)
                .addGap(30, 30, 30))
        );

        resultTablels.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultTablels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hội nghị", "Tên hội nghị", "Mô tả", "Thời gian bắt đầu", "Thời gian kêt thúc", "Địa điểm", "Xác nhận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultTablels.setRowHeight(24);
        resultTablels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTablelsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(resultTablels);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timkiemlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemlsActionPerformed
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        String hql = "select h,d.ten,y.xacNhan from YeuCau y join y.taiKhoan t join y.hoiNghi h "
        + "join h.diaDiem d where t.username =:username";
        if(tenls.getText().compareTo("")!=0)
        hql +=" and h.ten like '%" + tenls.getText()+"%'";
        if(diadiemls.getText().compareTo("")!=0)
        hql +=" and d.ten like '%" + diadiemls.getText()+"%'";
        if(motals.getText().compareTo("")!=0)
        hql +=" and h.moTaNgan like '%" + motals.getText()+"%'";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if(ngaydauls.getDate() != null)
        hql +=" and DATE(h.thoiGianBatDau) >='" + sdf.format(ngaydauls.getDate()) + "'";
        if(ngaysauls.getDate() != null)
        hql +=" and DATE(h.thoiGianBatDau) <='" + sdf.format(ngaysauls.getDate()) + "'";
        if(xacnhanls.getSelectedItem().toString().compareTo("Tất cả")!=0)
        hql +=" and y.xacNhan = '" + xacnhanls.getSelectedItem().toString()+ "'";
        Query q = session.createQuery(hql)
        .setParameter("username", tkLichSu.getText());
        List<Object[]> resultList = q.list();
        session.getTransaction().commit();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Mã hội nghị");
        tableHeaders.add("Tên hội nghị");
        tableHeaders.add("Mô tả");
        tableHeaders.add("Thời gian bắt đầu");
        tableHeaders.add("Thời gian kết thúc");
        tableHeaders.add("Địa điểm");
        tableHeaders.add("Xác nhận");
        for(Object[] o : resultList) {
            HoiNghi h =(HoiNghi)o[0];
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(h.getId());
            oneRow.add(h.getTen());
            oneRow.add(h.getMoTaNgan());
            oneRow.add(h.getThoiGianBatDau());
            oneRow.add(h.getThoiGianKetThuc());
            oneRow.add(o[1]);
            oneRow.add(o[2]);
            tableData.add(oneRow);
        }
        resultTablels.setModel(new DefaultTableModel(tableData, tableHeaders));
        resultTablels.setDefaultEditor(Object.class, null);
        resultTablels.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_timkiemlsActionPerformed

    private void dxLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxLichSuActionPerformed
        this.setVisible(false);
        new ManHinhChinh().setVisible(true);
    }//GEN-LAST:event_dxLichSuActionPerformed

    private void homelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelsMouseClicked
        this.setVisible(false);
        new ManHinhChinh(tkLichSu.getText(),matkLichSu.getText()).setVisible(true);
        manHinhChiTietHoiNghi.setVisible(false);
    }//GEN-LAST:event_homelsMouseClicked

    private void homelsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelsMouseEntered
        homels.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_homelsMouseEntered

    private void homelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelsMouseExited
        homels.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_homelsMouseExited

    private void profilelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelsMouseClicked
        this.setVisible(false);
        new Profile(tkLichSu.getText(),matkLichSu.getText()).setVisible(true);
        manHinhChiTietHoiNghi.setVisible(false);
    }//GEN-LAST:event_profilelsMouseClicked

    private void profilelsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelsMouseEntered
        profilels.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_profilelsMouseEntered

    private void profilelsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelsMouseExited
        profilels.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_profilelsMouseExited

    private void qlhnlsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnlsMouseEntered
        qlhnls.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_qlhnlsMouseEntered

    private void qlhnlsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnlsMouseExited
        qlhnls.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_qlhnlsMouseExited

    private void qluserlsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qluserlsMouseEntered
        qluserls.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_qluserlsMouseEntered

    private void qluserlsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qluserlsMouseExited
        qluserls.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_qluserlsMouseExited

    private void qluserlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qluserlsMouseClicked
        this.setVisible(false);
        new QuanLyUser(tkLichSu.getText(),matkLichSu.getText()).setVisible(true);
        manHinhChiTietHoiNghi.setVisible(false);
    }//GEN-LAST:event_qluserlsMouseClicked

    private void qlhnlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnlsMouseClicked
       this.setVisible(false);
       new QuanLyHoiNghi(tkLichSu.getText(),matkLichSu.getText()).setVisible(true);
       manHinhChiTietHoiNghi.setVisible(false);
    }//GEN-LAST:event_qlhnlsMouseClicked

    private void resultTablelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTablelsMouseClicked
        int index = resultTablels.getSelectedRow();
        TableModel model = resultTablels.getModel();
        String id = model.getValueAt(index, 0).toString();
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        List<Object[]> resultList = session.createQuery("select h,d from HoiNghi h join h.diaDiem d where h.id = :id")
        .setParameter("id",Integer.parseInt(id)).list();
        session.getTransaction().commit();
        Object o = resultList.get(0)[0];
        HoiNghi h = (HoiNghi)o;
        o = resultList.get(0)[1];
        DiaDiem d = (DiaDiem)o;
        manHinhChiTietHoiNghi.setVisible(true);
        manHinhChiTietHoiNghi.pack();
        manHinhChiTietHoiNghi.setLocationRelativeTo(null);
        manHinhChiTietHoiNghi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();
        if(h.getThoiGianBatDau().toString().compareTo(dtf.format(now))<=0)
            huydk.setVisible(false);
        ImageIcon icon = new ImageIcon(h.getHinhAnh());
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScale = new ImageIcon(imgScale);
        image.setIcon(iconScale);
        ma.setText(h.getId().toString());
        ten.setText(h.getTen());
        diaDiem.setText(d.getTen());
        diaChi.setText(d.getDiaChi());
        batDau.setText(h.getThoiGianBatDau().toString());
        ketThuc.setText(h.getThoiGianKetThuc().toString());
        moTa.setText(h.getMoTaDai());
        session.beginTransaction();
        List thamdu = session.createQuery("select t from YeuCau y join y.taiKhoan t where y.hoiNghi.id = :id and y.xacNhan = 'Đồng ý'")
        .setParameter("id",Integer.parseInt(id)).list();
        session.getTransaction().commit();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Tên người tham dự"); 
        tableHeaders.add("Email"); 
        for(Object ob : thamdu) {
            TaiKhoan t =(TaiKhoan)ob;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(t.getTen());
            oneRow.add(t.getEmail());
            tableData.add(oneRow);
        }
        thamduTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        thamduTable.setDefaultEditor(Object.class, null);
        thamduTable.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 18));
        thamduTable.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_resultTablelsMouseClicked

    private void huydkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huydkActionPerformed
        Object[] options = {"Đồng ý","Hủy"};
        int YesOrNo = JOptionPane.showOptionDialog(null,
            "Xác nhận hủy đăng ký ?",
            "Thông báo",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[1]);
        if(YesOrNo == 0)
        {
            int index = resultTablels.getSelectedRow();
            TableModel model = resultTablels.getModel();
            String idhn = model.getValueAt(index, 0).toString();
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q =session.createSQLQuery("delete from yeu_cau where id_tk = :idtk and id_hn = :idhn");
            q.setParameter("idtk",Integer.parseInt(matkLichSu.getText()));
            q.setParameter("idhn",Integer.parseInt(idhn));
            q.executeUpdate();
            session.getTransaction().commit();
            JOptionPane.showMessageDialog(null,"Hủy đăng ký thành công!!.","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            displayTable();
            manHinhChiTietHoiNghi.setVisible(false);
        }
    }//GEN-LAST:event_huydkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSuDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel batDau;
    public javax.swing.JLabel diaChi;
    public javax.swing.JLabel diaDiem;
    private javax.swing.JTextField diadiemls;
    private javax.swing.JButton dxLichSu;
    private javax.swing.JPanel homels;
    private javax.swing.JButton huydk;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel ketThuc;
    private javax.swing.JPanel lsdkls;
    public javax.swing.JLabel ma;
    private javax.swing.JFrame manHinhChiTietHoiNghi;
    private javax.swing.JLabel matkLichSu;
    public javax.swing.JTextPane moTa;
    private javax.swing.JTextField motals;
    private com.toedter.calendar.JDateChooser ngaydauls;
    private com.toedter.calendar.JDateChooser ngaysauls;
    private javax.swing.JPanel profilels;
    private javax.swing.JPanel qlhnls;
    private javax.swing.JPanel qluserls;
    private javax.swing.JTable resultTablels;
    public javax.swing.JLabel ten;
    private javax.swing.JTextField tenls;
    private javax.swing.JTable thamduTable;
    private javax.swing.JButton timkiemls;
    private javax.swing.JLabel tkLichSu;
    private javax.swing.JComboBox<String> xacnhanls;
    // End of variables declaration//GEN-END:variables
}
