/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlhoinghi.ui;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.Query;
import qlhoinghi.entity.HoiNghi;
import qlhoinghi.entity.TaiKhoan;
import qlhoinghi.util.HibernateUtil;

/**
 *
 * @author admin
 */
public class QuanLyUser extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyUser
     */
    public QuanLyUser() {
        initComponents();
    }
    public QuanLyUser(String username,String id) {
        initComponents();
        tkUser.setText(username);
        matkUser.setText(id);
        matkUser.setVisible(false);
        dxUser.setVisible(true);
        qluseru.setBackground(new java.awt.Color(204,204,255));
        displayTable();
    }
    public void displayTable()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery("select t from TaiKhoan t where t.username != 'admin'");
        List resultList = q.list();
        session.getTransaction().commit();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Mã tài khoản"); 
        tableHeaders.add("Username"); 
        tableHeaders.add("Password");
        tableHeaders.add("Tên"); 
        tableHeaders.add("Email");
        tableHeaders.add("Truy cập"); 
        for(Object o : resultList) {
            TaiKhoan t =(TaiKhoan)o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(t.getId());
            oneRow.add(t.getUsername());
            oneRow.add(t.getPass());
            oneRow.add(t.getTen());
            oneRow.add(t.getEmail());
            if(t.isTruyCap())
                oneRow.add("Được phép");
            else oneRow.add("Cấm");
            tableData.add(oneRow);
        }
        resultTableu.setModel(new DefaultTableModel(tableData, tableHeaders));
        resultTableu.setDefaultEditor(Object.class, null);
        resultTableu.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 18));
        resultTableu.setAutoCreateRowSorter(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thaydoiquyen = new javax.swing.JDialog();
        suatruycap = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        masuatruycap = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        xacnhan = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        homeu = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        profileu = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        qlhnu = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        qluseru = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lsdku = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tkUser = new javax.swing.JLabel();
        dxUser = new javax.swing.JButton();
        matkUser = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        mau = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        emailu = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        truycap = new javax.swing.JComboBox<>();
        timkiemu = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        u = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultTableu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        thaydoitruycap = new javax.swing.JButton();

        thaydoiquyen.setTitle("Thay đổi quyền truy cập");
        thaydoiquyen.setMinimumSize(new java.awt.Dimension(465, 300));
        thaydoiquyen.setModal(true);

        suatruycap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Được phép", "Cấm" }));
        suatruycap.setToolTipText("");

        jLabel29.setText("Mã tài khoản");

        jLabel36.setText("Truy cập");

        xacnhan.setText("Xác nhận");
        xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thaydoiquyenLayout = new javax.swing.GroupLayout(thaydoiquyen.getContentPane());
        thaydoiquyen.getContentPane().setLayout(thaydoiquyenLayout);
        thaydoiquyenLayout.setHorizontalGroup(
            thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thaydoiquyenLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel36))
                .addGap(32, 32, 32)
                .addGroup(thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masuatruycap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suatruycap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
            .addGroup(thaydoiquyenLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(xacnhan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thaydoiquyenLayout.setVerticalGroup(
            thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thaydoiquyenLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(masuatruycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(thaydoiquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(suatruycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(xacnhan)
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý User");
        setResizable(false);

        jPanel11.setBackground(new java.awt.Color(102, 102, 255));

        homeu.setBackground(new java.awt.Color(102, 102, 255));
        homeu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeuMouseExited(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(204, 204, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-24 (1).png"))); // NOI18N
        jLabel31.setText("Trang chủ");

        javax.swing.GroupLayout homeuLayout = new javax.swing.GroupLayout(homeu);
        homeu.setLayout(homeuLayout);
        homeuLayout.setHorizontalGroup(
            homeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeuLayout.setVerticalGroup(
            homeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        profileu.setBackground(new java.awt.Color(102, 102, 255));
        profileu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileuMouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-male-user-24.png"))); // NOI18N
        jLabel32.setText("Profile");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout profileuLayout = new javax.swing.GroupLayout(profileu);
        profileu.setLayout(profileuLayout);
        profileuLayout.setHorizontalGroup(
            profileuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileuLayout.setVerticalGroup(
            profileuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32))
        );

        qlhnu.setBackground(new java.awt.Color(102, 102, 255));
        qlhnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlhnuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qlhnuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qlhnuMouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-management-24.png"))); // NOI18N
        jLabel33.setText("Quản lý hội nghị");

        javax.swing.GroupLayout qlhnuLayout = new javax.swing.GroupLayout(qlhnu);
        qlhnu.setLayout(qlhnuLayout);
        qlhnuLayout.setHorizontalGroup(
            qlhnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        qlhnuLayout.setVerticalGroup(
            qlhnuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlhnuLayout.createSequentialGroup()
                .addComponent(jLabel33)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        qluseru.setBackground(new java.awt.Color(102, 102, 255));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-management-24 (1).png"))); // NOI18N
        jLabel34.setText("Quản lý user");

        javax.swing.GroupLayout qluseruLayout = new javax.swing.GroupLayout(qluseru);
        qluseru.setLayout(qluseruLayout);
        qluseruLayout.setHorizontalGroup(
            qluseruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        qluseruLayout.setVerticalGroup(
            qluseruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qluseruLayout.createSequentialGroup()
                .addComponent(jLabel34)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lsdku.setBackground(new java.awt.Color(102, 102, 255));
        lsdku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsdkuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lsdkuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lsdkuMouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-activity-history-24.png"))); // NOI18N
        jLabel35.setText("Lịch sử đăng ký");

        javax.swing.GroupLayout lsdkuLayout = new javax.swing.GroupLayout(lsdku);
        lsdku.setLayout(lsdkuLayout);
        lsdkuLayout.setHorizontalGroup(
            lsdkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lsdkuLayout.setVerticalGroup(
            lsdkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsdkuLayout.createSequentialGroup()
                .addComponent(jLabel35)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lsdku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qlhnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(qluseru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(homeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(profileu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lsdku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(qlhnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(qluseru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 51));

        tkUser.setText("đây là tk");

        dxUser.setText("Đăng xuất");
        dxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dxUserActionPerformed(evt);
            }
        });

        matkUser.setText("đây là mã");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(matkUser)
                .addGap(31, 31, 31)
                .addComponent(tkUser)
                .addGap(18, 18, 18)
                .addComponent(dxUser)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dxUser)
                    .addComponent(tkUser)
                    .addComponent(matkUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("Mã tài khoản");

        jLabel26.setText("Email");

        jLabel27.setText("Tên");

        jLabel30.setText("Truy cập");

        truycap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Được phép", "Cấm" }));
        truycap.setToolTipText("");

        timkiemu.setText("Tìm kiếm");
        timkiemu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemuActionPerformed(evt);
            }
        });

        jLabel28.setText("Username");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel25)
                .addGap(32, 32, 32)
                .addComponent(mau, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel27)
                .addGap(72, 72, 72)
                .addComponent(ten)
                .addGap(56, 56, 56)
                .addComponent(jLabel28)
                .addGap(72, 72, 72)
                .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(74, 74, 74)
                .addComponent(emailu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel30)
                .addGap(70, 70, 70)
                .addComponent(truycap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(timkiemu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(truycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(emailu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(timkiemu)
                .addGap(25, 25, 25))
        );

        resultTableu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultTableu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã tài khoản", "Username", "Password", "Tên", "Email", "Truy cập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultTableu.setRowHeight(24);
        jScrollPane5.setViewportView(resultTableu);

        thaydoitruycap.setText("Thay đổi quyền truy cập");
        thaydoitruycap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thaydoitruycapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(thaydoitruycap)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(thaydoitruycap)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeuMouseClicked
        this.setVisible(false);
        new ManHinhChinh(tkUser.getText(),matkUser.getText()).setVisible(true);
    }//GEN-LAST:event_homeuMouseClicked

    private void homeuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeuMouseEntered
        homeu.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_homeuMouseEntered

    private void homeuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeuMouseExited
        homeu.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_homeuMouseExited

    private void qlhnuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnuMouseEntered
        qlhnu.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_qlhnuMouseEntered

    private void qlhnuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnuMouseExited
        qlhnu.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_qlhnuMouseExited

    private void lsdkuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsdkuMouseClicked
        this.setVisible(false);
        new LichSuDangKy(tkUser.getText(),matkUser.getText()).setVisible(true);
    }//GEN-LAST:event_lsdkuMouseClicked

    private void lsdkuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsdkuMouseEntered
        lsdku.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_lsdkuMouseEntered

    private void lsdkuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsdkuMouseExited
        lsdku.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_lsdkuMouseExited

    private void dxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dxUserActionPerformed
        this.setVisible(false);
        new ManHinhChinh().setVisible(true);
    }//GEN-LAST:event_dxUserActionPerformed

    private void timkiemuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemuActionPerformed
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        String hql = "select t from TaiKhoan t where t.username != 'admin'";
        if(mau.getText().compareTo("")!=0)
        hql +=" and t.id = " + mau.getText();
        if(ten.getText().compareTo("")!=0)
        hql +=" and t.ten like '%" + ten.getText()+"%'";
        if(u.getText().compareTo("")!=0)
        hql +=" and t.username like '%" + u.getText()+"%'";
        if(emailu.getText().compareTo("")!=0)
        hql +=" and t.email like '%" + emailu.getText()+"%'";
        if(truycap.getSelectedItem().toString().compareTo("Được phép")==0)
        hql +=" and t.truyCap = true";
        if(truycap.getSelectedItem().toString().compareTo("Cấm")==0)
        hql +=" and t.truyCap = false";
        Query q = session.createQuery(hql);
        List resultList = q.list();
        session.getTransaction().commit();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        tableHeaders.add("Mã tài khoản"); 
        tableHeaders.add("Username"); 
        tableHeaders.add("Password");
        tableHeaders.add("Tên"); 
        tableHeaders.add("Email");
        tableHeaders.add("Truy cập"); 
        for(Object o : resultList) {
            TaiKhoan t =(TaiKhoan)o;
            Vector<Object> oneRow = new Vector<Object>();
            oneRow.add(t.getId());
            oneRow.add(t.getUsername());
            oneRow.add(t.getPass());
            oneRow.add(t.getTen());
            oneRow.add(t.getEmail());
            if(t.isTruyCap())
                oneRow.add("Được phép");
            else oneRow.add("Cấm");
            tableData.add(oneRow);
        }
        resultTableu.setModel(new DefaultTableModel(tableData, tableHeaders));
        resultTableu.setDefaultEditor(Object.class, null);
        resultTableu.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 18));
        resultTableu.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_timkiemuActionPerformed

    private void profileuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileuMouseClicked
        this.setVisible(false);
        new Profile(tkUser.getText(),matkUser.getText()).setVisible(true);
    }//GEN-LAST:event_profileuMouseClicked

    private void profileuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileuMouseEntered
        profileu.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_profileuMouseEntered

    private void profileuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileuMouseExited
        profileu.setBackground(new java.awt.Color(102,102,255));
    }//GEN-LAST:event_profileuMouseExited

    private void thaydoitruycapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thaydoitruycapActionPerformed
        thaydoiquyen.setLocationRelativeTo(null);
        thaydoiquyen.setVisible(true);
    }//GEN-LAST:event_thaydoitruycapActionPerformed

    private void xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanActionPerformed
        if (masuatruycap.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(null,"Không được để trống mã tài khoản!!.","Thông báo",JOptionPane.ERROR_MESSAGE);
        else
        {
             Object[] options = {"Đồng ý","Hủy"};
            int YesOrNo = JOptionPane.showOptionDialog(null,
                "Xác nhận đổi quyền truy cập ?",
                "Thông báo",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
            if(YesOrNo == 0)
            {
                Session session = HibernateUtil.getSessionFactory().openSession();
                session.beginTransaction();
                String hql;
                if(suatruycap.getSelectedItem().toString().compareTo("Cấm") == 0)
                    hql = ("update tai_khoan set truy_cap = false where id = :id");
                else hql = ("update tai_khoan set truy_cap = true where id  = :id");
                Query q =session.createSQLQuery(hql);
                q.setParameter("id",masuatruycap.getText());
                int n = q.executeUpdate();
                session.getTransaction().commit();
                if(n>0)
                {
                    JOptionPane.showMessageDialog(null,"Đổi quyền truy cập thành công!!.","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    displayTable();
                }
                    else JOptionPane.showMessageDialog(null,"Mã tài khoản không tồn tại!!.","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_xacnhanActionPerformed

    private void qlhnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlhnuMouseClicked
        this.setVisible(false);
        new QuanLyHoiNghi(tkUser.getText(),matkUser.getText()).setVisible(true);
    }//GEN-LAST:event_qlhnuMouseClicked

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dxUser;
    private javax.swing.JTextField emailu;
    private javax.swing.JPanel homeu;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel lsdku;
    private javax.swing.JTextField masuatruycap;
    private javax.swing.JLabel matkUser;
    private javax.swing.JTextField mau;
    private javax.swing.JPanel profileu;
    private javax.swing.JPanel qlhnu;
    private javax.swing.JPanel qluseru;
    private javax.swing.JTable resultTableu;
    private javax.swing.JComboBox<String> suatruycap;
    private javax.swing.JTextField ten;
    private javax.swing.JDialog thaydoiquyen;
    private javax.swing.JButton thaydoitruycap;
    private javax.swing.JButton timkiemu;
    private javax.swing.JLabel tkUser;
    private javax.swing.JComboBox<String> truycap;
    private javax.swing.JTextField u;
    private javax.swing.JButton xacnhan;
    // End of variables declaration//GEN-END:variables
}
