package qlhoinghi.entity;
// Generated Jul 9, 2020 3:16:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DiaDiem generated by hbm2java
 */
public class DiaDiem  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private String diaChi;
     private int sucChua;
     private Set hoiNghis = new HashSet(0);

    public DiaDiem() {
    }

	
    public DiaDiem(String ten, String diaChi, int sucChua) {
        this.ten = ten;
        this.diaChi = diaChi;
        this.sucChua = sucChua;
    }
    public DiaDiem(String ten, String diaChi, int sucChua, Set hoiNghis) {
       this.ten = ten;
       this.diaChi = diaChi;
       this.sucChua = sucChua;
       this.hoiNghis = hoiNghis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public int getSucChua() {
        return this.sucChua;
    }
    
    public void setSucChua(int sucChua) {
        this.sucChua = sucChua;
    }
    public Set getHoiNghis() {
        return this.hoiNghis;
    }
    
    public void setHoiNghis(Set hoiNghis) {
        this.hoiNghis = hoiNghis;
    }




}


