package qlhoinghi.entity;
// Generated Jul 9, 2020 3:16:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoiNghi generated by hbm2java
 */
public class HoiNghi  implements java.io.Serializable {


     private Integer id;
     private DiaDiem diaDiem;
     private String ten;
     private String moTaNgan;
     private String moTaDai;
     private String hinhAnh;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private int soNguoiThamDu;
     private Set yeuCaus = new HashSet(0);

    public HoiNghi() {
    }

	
    public HoiNghi(DiaDiem diaDiem, String ten, String moTaNgan, String moTaDai, String hinhAnh, Date thoiGianBatDau, Date thoiGianKetThuc, int soNguoiThamDu) {
        this.diaDiem = diaDiem;
        this.ten = ten;
        this.moTaNgan = moTaNgan;
        this.moTaDai = moTaDai;
        this.hinhAnh = hinhAnh;
        this.thoiGianBatDau = thoiGianBatDau;
        this.thoiGianKetThuc = thoiGianKetThuc;
        this.soNguoiThamDu = soNguoiThamDu;
    }
    public HoiNghi(DiaDiem diaDiem, String ten, String moTaNgan, String moTaDai, String hinhAnh, Date thoiGianBatDau, Date thoiGianKetThuc, int soNguoiThamDu, Set yeuCaus) {
       this.diaDiem = diaDiem;
       this.ten = ten;
       this.moTaNgan = moTaNgan;
       this.moTaDai = moTaDai;
       this.hinhAnh = hinhAnh;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.soNguoiThamDu = soNguoiThamDu;
       this.yeuCaus = yeuCaus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DiaDiem getDiaDiem() {
        return this.diaDiem;
    }
    
    public void setDiaDiem(DiaDiem diaDiem) {
        this.diaDiem = diaDiem;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMoTaNgan() {
        return this.moTaNgan;
    }
    
    public void setMoTaNgan(String moTaNgan) {
        this.moTaNgan = moTaNgan;
    }
    public String getMoTaDai() {
        return this.moTaDai;
    }
    
    public void setMoTaDai(String moTaDai) {
        this.moTaDai = moTaDai;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public int getSoNguoiThamDu() {
        return this.soNguoiThamDu;
    }
    
    public void setSoNguoiThamDu(int soNguoiThamDu) {
        this.soNguoiThamDu = soNguoiThamDu;
    }
    public Set getYeuCaus() {
        return this.yeuCaus;
    }
    
    public void setYeuCaus(Set yeuCaus) {
        this.yeuCaus = yeuCaus;
    }




}


