package qlhoinghi.entity;
// Generated Jul 9, 2020 3:16:50 PM by Hibernate Tools 4.3.1


/**
 * YeuCau generated by hbm2java
 */
public class YeuCau  implements java.io.Serializable {


     private Integer id;
     private HoiNghi hoiNghi;
     private TaiKhoan taiKhoan;
     private String xacNhan;

    public YeuCau() {
    }

	
    public YeuCau(HoiNghi hoiNghi, TaiKhoan taiKhoan) {
        this.hoiNghi = hoiNghi;
        this.taiKhoan = taiKhoan;
    }
    public YeuCau(HoiNghi hoiNghi, TaiKhoan taiKhoan, String xacNhan) {
       this.hoiNghi = hoiNghi;
       this.taiKhoan = taiKhoan;
       this.xacNhan = xacNhan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public HoiNghi getHoiNghi() {
        return this.hoiNghi;
    }
    
    public void setHoiNghi(HoiNghi hoiNghi) {
        this.hoiNghi = hoiNghi;
    }
    public TaiKhoan getTaiKhoan() {
        return this.taiKhoan;
    }
    
    public void setTaiKhoan(TaiKhoan taiKhoan) {
        this.taiKhoan = taiKhoan;
    }
    public String getXacNhan() {
        return this.xacNhan;
    }
    
    public void setXacNhan(String xacNhan) {
        this.xacNhan = xacNhan;
    }




}


